name: Create and publish a Docker image to hub.docker.com

on:
  push:
    branches:
      - main

jobs:
  build:
    if: github.repository == 'scilifelabdatacentre/shiny-adhd-medication-sweden'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish to Docker Hub
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: scilifelabdatacentre/shiny-adhd-medication-sweden
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          dockerfile: Dockerfile
          tags: "latest"
